package common

const (
	LAN_ZH_HANS = "zh-hans"
	LAN_ZH_HANT = "zh-hant"
	LAN_EN      = "en"
)

const (
	STRING_KEY_BOSS_HAS_BEEN_DEFEATED   = "BOSS_HAS_BEEN_DEFEATED"
	STRING_KEY_BOSS_DIED_OR_ESCAPED     = "BOSS_DIED_OR_ESCAPED"
	STRING_KEY_BOSS_INVITE              = "BOSS_INVITE"
	STRING_KEY_BOSS_APPEARED            = "BOSS_APPEARED"
	STRING_KEY_BOSS_COME_TO_FIGHT       = "BOSS_COME_TO_FIGHT"
	STRING_KEY_BOSS_REWARDS_TITLE       = "BOSS_REWARDS_TITLE"
	STRING_KEY_BOSS_REWARDS             = "BOSS_REWARDS"
	STRING_KEY_BOSS_LEVEL               = "BOSS_LEVEL"
	STRING_KEY_BOSS_HP                  = "BOSS_HP"
	STRING_KEY_BOSS_FIGHT_TITLE         = "BOSS_FIGHT_TITLE"
	STRING_KEY_BOSS_EXPIRE_AT           = "BOSS_EXPIRE_AT"
	STRING_KEY_BOSS_DMG_CASED_BY_PLAYER = "BOSS_DMG_CASED_BY_PLAYER"
	STRING_KEY_BOSS_WIN_REWARDS         = "BOSS_WIN_REWARDS"
	STRING_KEY_BOSS_WIN_NO_REWARDS      = "BOSS_WIN_NO_REWARDS"

	STRING_KEY_BUTTON_FIGHT = "BUTTON_FIGHT"

	STRING_KEY_ERR_IN_FIGHT_CD               = "ERR_IN_FIGHT_CD"
	STRING_KEY_ERR_NO_REQUESTED_NFT_WEAPON   = "ERR_NO_REQUESTED_NFT_WEAPON"
	STRING_KEY_ERR_NOT_MEET_NFT_WEAPON_LEVEL = "ERR_NOT_MEET_NFT_WEAPON_LEVEL"
	STRING_KEY_ERR_ALREADY_FOUGHT            = "ERR_ALREADY_FOUGHT"
)
