// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc_apiproxy.proto

package mpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	APIProxyGRPC_SendEmailBindCode_FullMethodName                    = "/mpb.APIProxyGRPC/SendEmailBindCode"
	APIProxyGRPC_SendEmailResetPasswordValidationCode_FullMethodName = "/mpb.APIProxyGRPC/SendEmailResetPasswordValidationCode"
	APIProxyGRPC_SendMsgToTelegram_FullMethodName                    = "/mpb.APIProxyGRPC/SendMsgToTelegram"
	APIProxyGRPC_GenerateShareHBossLink_FullMethodName               = "/mpb.APIProxyGRPC/GenerateShareHBossLink"
)

// APIProxyGRPCClient is the client API for APIProxyGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIProxyGRPCClient interface {
	SendEmailBindCode(ctx context.Context, in *ReqSendEmailBindCode, opts ...grpc.CallOption) (*Empty, error)
	SendEmailResetPasswordValidationCode(ctx context.Context, in *ReqSendEmailResetPasswordValidationCode, opts ...grpc.CallOption) (*Empty, error)
	SendMsgToTelegram(ctx context.Context, in *ReqSendMsgToTelegram, opts ...grpc.CallOption) (*Empty, error)
	GenerateShareHBossLink(ctx context.Context, in *ReqGenerateShareHBossLink, opts ...grpc.CallOption) (*ResGenerateShareHBossLink, error)
}

type aPIProxyGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIProxyGRPCClient(cc grpc.ClientConnInterface) APIProxyGRPCClient {
	return &aPIProxyGRPCClient{cc}
}

func (c *aPIProxyGRPCClient) SendEmailBindCode(ctx context.Context, in *ReqSendEmailBindCode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, APIProxyGRPC_SendEmailBindCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) SendEmailResetPasswordValidationCode(ctx context.Context, in *ReqSendEmailResetPasswordValidationCode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, APIProxyGRPC_SendEmailResetPasswordValidationCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) SendMsgToTelegram(ctx context.Context, in *ReqSendMsgToTelegram, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, APIProxyGRPC_SendMsgToTelegram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) GenerateShareHBossLink(ctx context.Context, in *ReqGenerateShareHBossLink, opts ...grpc.CallOption) (*ResGenerateShareHBossLink, error) {
	out := new(ResGenerateShareHBossLink)
	err := c.cc.Invoke(ctx, APIProxyGRPC_GenerateShareHBossLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIProxyGRPCServer is the server API for APIProxyGRPC service.
// All implementations must embed UnimplementedAPIProxyGRPCServer
// for forward compatibility
type APIProxyGRPCServer interface {
	SendEmailBindCode(context.Context, *ReqSendEmailBindCode) (*Empty, error)
	SendEmailResetPasswordValidationCode(context.Context, *ReqSendEmailResetPasswordValidationCode) (*Empty, error)
	SendMsgToTelegram(context.Context, *ReqSendMsgToTelegram) (*Empty, error)
	GenerateShareHBossLink(context.Context, *ReqGenerateShareHBossLink) (*ResGenerateShareHBossLink, error)
	mustEmbedUnimplementedAPIProxyGRPCServer()
}

// UnimplementedAPIProxyGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedAPIProxyGRPCServer struct {
}

func (UnimplementedAPIProxyGRPCServer) SendEmailBindCode(context.Context, *ReqSendEmailBindCode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailBindCode not implemented")
}
func (UnimplementedAPIProxyGRPCServer) SendEmailResetPasswordValidationCode(context.Context, *ReqSendEmailResetPasswordValidationCode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailResetPasswordValidationCode not implemented")
}
func (UnimplementedAPIProxyGRPCServer) SendMsgToTelegram(context.Context, *ReqSendMsgToTelegram) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsgToTelegram not implemented")
}
func (UnimplementedAPIProxyGRPCServer) GenerateShareHBossLink(context.Context, *ReqGenerateShareHBossLink) (*ResGenerateShareHBossLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShareHBossLink not implemented")
}
func (UnimplementedAPIProxyGRPCServer) mustEmbedUnimplementedAPIProxyGRPCServer() {}

// UnsafeAPIProxyGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIProxyGRPCServer will
// result in compilation errors.
type UnsafeAPIProxyGRPCServer interface {
	mustEmbedUnimplementedAPIProxyGRPCServer()
}

func RegisterAPIProxyGRPCServer(s grpc.ServiceRegistrar, srv APIProxyGRPCServer) {
	s.RegisterService(&APIProxyGRPC_ServiceDesc, srv)
}

func _APIProxyGRPC_SendEmailBindCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSendEmailBindCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).SendEmailBindCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_SendEmailBindCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).SendEmailBindCode(ctx, req.(*ReqSendEmailBindCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_SendEmailResetPasswordValidationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSendEmailResetPasswordValidationCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).SendEmailResetPasswordValidationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_SendEmailResetPasswordValidationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).SendEmailResetPasswordValidationCode(ctx, req.(*ReqSendEmailResetPasswordValidationCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_SendMsgToTelegram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSendMsgToTelegram)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).SendMsgToTelegram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_SendMsgToTelegram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).SendMsgToTelegram(ctx, req.(*ReqSendMsgToTelegram))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_GenerateShareHBossLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGenerateShareHBossLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).GenerateShareHBossLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_GenerateShareHBossLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).GenerateShareHBossLink(ctx, req.(*ReqGenerateShareHBossLink))
	}
	return interceptor(ctx, in, info, handler)
}

// APIProxyGRPC_ServiceDesc is the grpc.ServiceDesc for APIProxyGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIProxyGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpb.APIProxyGRPC",
	HandlerType: (*APIProxyGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailBindCode",
			Handler:    _APIProxyGRPC_SendEmailBindCode_Handler,
		},
		{
			MethodName: "SendEmailResetPasswordValidationCode",
			Handler:    _APIProxyGRPC_SendEmailResetPasswordValidationCode_Handler,
		},
		{
			MethodName: "SendMsgToTelegram",
			Handler:    _APIProxyGRPC_SendMsgToTelegram_Handler,
		},
		{
			MethodName: "GenerateShareHBossLink",
			Handler:    _APIProxyGRPC_GenerateShareHBossLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_apiproxy.proto",
}
