// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc_account.proto

package mpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountService_LoginTest_FullMethodName                 = "/mpb.AccountService/LoginTest"
	AccountService_GenerateLoginToken_FullMethodName        = "/mpb.AccountService/GenerateLoginToken"
	AccountService_LoginByToken_FullMethodName              = "/mpb.AccountService/LoginByToken"
	AccountService_GetAccountByTGUser_FullMethodName        = "/mpb.AccountService/GetAccountByTGUser"
	AccountService_GetAccountByUserId_FullMethodName        = "/mpb.AccountService/GetAccountByUserId"
	AccountService_BatchGetAccountsByUserIds_FullMethodName = "/mpb.AccountService/BatchGetAccountsByUserIds"
	AccountService_SetAccountTGLan_FullMethodName           = "/mpb.AccountService/SetAccountTGLan"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	// rpc RegisterAccount(ReqRegisterAccount) returns (AccountInfo);
	//
	//	rpc LoginByPassword(ReqLoginByPassword) returns (ResLoginByPassword);
	//	rpc GetAccountInfo(ReqUserId) returns (AccountInfo);
	//	rpc GetAccountInfoByAccount(ReqGetAccountInfoByAccount) returns (AccountInfo);
	//	rpc GenerateNonce(Empty) returns (ResGenerateNonce);
	//	rpc WebLoginByWallet(ReqWebLoginByWallet) returns (ResWebLoginByWallet);
	//	rpc GenerateAndSendEmailBindCode(ReqGenerateAndSendEmailBindCode) returns (Empty);
	//	rpc WebBindEmail(ReqWebBindEmail) returns (ResWebBindEmail);
	//	rpc GetAptosAccount(ReqUserId) returns (ResGetAptosAccount);
	//	rpc ChangePassword(ReqChangePassword) returns (Empty);
	//	rpc SendEmailResetPasswordCode(ReqSendEmailResetPasswordCode) returns (Empty);
	//	rpc CheckEmailResetPasswordCode(ReqCheckEmailResetPasswordCode) returns (ResCheckEmailResetPasswordCode);
	//	rpc ResetPasswordByEmail(ReqResetPasswordByEmail) returns (Empty);
	//	rpc ResetPasswordByEmailAndVCode(ReqResetPasswordByEmailAndVCode) returns (Empty);
	//	rpc BatchGetAccountsByWalletAddrs (ReqBatchGetAccountsByWalletAddrs) returns (ResBatchGetAccountsByWalletAddrs);
	LoginTest(ctx context.Context, in *ReqUserId, opts ...grpc.CallOption) (*ResLoginTest, error)
	GenerateLoginToken(ctx context.Context, in *ReqGenerateLoginToken, opts ...grpc.CallOption) (*ResGenerateLoginToken, error)
	LoginByToken(ctx context.Context, in *ReqLoginByToken, opts ...grpc.CallOption) (*ResLoginByToken, error)
	GetAccountByTGUser(ctx context.Context, in *ReqGetAccountByTGUser, opts ...grpc.CallOption) (*ResGetAccountByTGUser, error)
	GetAccountByUserId(ctx context.Context, in *ReqUserId, opts ...grpc.CallOption) (*ResGetAccountByUserId, error)
	BatchGetAccountsByUserIds(ctx context.Context, in *ReqUserIds, opts ...grpc.CallOption) (*ResBatchGetAccountsByUserIds, error)
	SetAccountTGLan(ctx context.Context, in *ReqSetAccountTGLan, opts ...grpc.CallOption) (*Empty, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) LoginTest(ctx context.Context, in *ReqUserId, opts ...grpc.CallOption) (*ResLoginTest, error) {
	out := new(ResLoginTest)
	err := c.cc.Invoke(ctx, AccountService_LoginTest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GenerateLoginToken(ctx context.Context, in *ReqGenerateLoginToken, opts ...grpc.CallOption) (*ResGenerateLoginToken, error) {
	out := new(ResGenerateLoginToken)
	err := c.cc.Invoke(ctx, AccountService_GenerateLoginToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) LoginByToken(ctx context.Context, in *ReqLoginByToken, opts ...grpc.CallOption) (*ResLoginByToken, error) {
	out := new(ResLoginByToken)
	err := c.cc.Invoke(ctx, AccountService_LoginByToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountByTGUser(ctx context.Context, in *ReqGetAccountByTGUser, opts ...grpc.CallOption) (*ResGetAccountByTGUser, error) {
	out := new(ResGetAccountByTGUser)
	err := c.cc.Invoke(ctx, AccountService_GetAccountByTGUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountByUserId(ctx context.Context, in *ReqUserId, opts ...grpc.CallOption) (*ResGetAccountByUserId, error) {
	out := new(ResGetAccountByUserId)
	err := c.cc.Invoke(ctx, AccountService_GetAccountByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) BatchGetAccountsByUserIds(ctx context.Context, in *ReqUserIds, opts ...grpc.CallOption) (*ResBatchGetAccountsByUserIds, error) {
	out := new(ResBatchGetAccountsByUserIds)
	err := c.cc.Invoke(ctx, AccountService_BatchGetAccountsByUserIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SetAccountTGLan(ctx context.Context, in *ReqSetAccountTGLan, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, AccountService_SetAccountTGLan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility
type AccountServiceServer interface {
	// rpc RegisterAccount(ReqRegisterAccount) returns (AccountInfo);
	//
	//	rpc LoginByPassword(ReqLoginByPassword) returns (ResLoginByPassword);
	//	rpc GetAccountInfo(ReqUserId) returns (AccountInfo);
	//	rpc GetAccountInfoByAccount(ReqGetAccountInfoByAccount) returns (AccountInfo);
	//	rpc GenerateNonce(Empty) returns (ResGenerateNonce);
	//	rpc WebLoginByWallet(ReqWebLoginByWallet) returns (ResWebLoginByWallet);
	//	rpc GenerateAndSendEmailBindCode(ReqGenerateAndSendEmailBindCode) returns (Empty);
	//	rpc WebBindEmail(ReqWebBindEmail) returns (ResWebBindEmail);
	//	rpc GetAptosAccount(ReqUserId) returns (ResGetAptosAccount);
	//	rpc ChangePassword(ReqChangePassword) returns (Empty);
	//	rpc SendEmailResetPasswordCode(ReqSendEmailResetPasswordCode) returns (Empty);
	//	rpc CheckEmailResetPasswordCode(ReqCheckEmailResetPasswordCode) returns (ResCheckEmailResetPasswordCode);
	//	rpc ResetPasswordByEmail(ReqResetPasswordByEmail) returns (Empty);
	//	rpc ResetPasswordByEmailAndVCode(ReqResetPasswordByEmailAndVCode) returns (Empty);
	//	rpc BatchGetAccountsByWalletAddrs (ReqBatchGetAccountsByWalletAddrs) returns (ResBatchGetAccountsByWalletAddrs);
	LoginTest(context.Context, *ReqUserId) (*ResLoginTest, error)
	GenerateLoginToken(context.Context, *ReqGenerateLoginToken) (*ResGenerateLoginToken, error)
	LoginByToken(context.Context, *ReqLoginByToken) (*ResLoginByToken, error)
	GetAccountByTGUser(context.Context, *ReqGetAccountByTGUser) (*ResGetAccountByTGUser, error)
	GetAccountByUserId(context.Context, *ReqUserId) (*ResGetAccountByUserId, error)
	BatchGetAccountsByUserIds(context.Context, *ReqUserIds) (*ResBatchGetAccountsByUserIds, error)
	SetAccountTGLan(context.Context, *ReqSetAccountTGLan) (*Empty, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (UnimplementedAccountServiceServer) LoginTest(context.Context, *ReqUserId) (*ResLoginTest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginTest not implemented")
}
func (UnimplementedAccountServiceServer) GenerateLoginToken(context.Context, *ReqGenerateLoginToken) (*ResGenerateLoginToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateLoginToken not implemented")
}
func (UnimplementedAccountServiceServer) LoginByToken(context.Context, *ReqLoginByToken) (*ResLoginByToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByToken not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountByTGUser(context.Context, *ReqGetAccountByTGUser) (*ResGetAccountByTGUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByTGUser not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountByUserId(context.Context, *ReqUserId) (*ResGetAccountByUserId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByUserId not implemented")
}
func (UnimplementedAccountServiceServer) BatchGetAccountsByUserIds(context.Context, *ReqUserIds) (*ResBatchGetAccountsByUserIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetAccountsByUserIds not implemented")
}
func (UnimplementedAccountServiceServer) SetAccountTGLan(context.Context, *ReqSetAccountTGLan) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAccountTGLan not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_LoginTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).LoginTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_LoginTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).LoginTest(ctx, req.(*ReqUserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GenerateLoginToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGenerateLoginToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GenerateLoginToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GenerateLoginToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GenerateLoginToken(ctx, req.(*ReqGenerateLoginToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_LoginByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLoginByToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).LoginByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_LoginByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).LoginByToken(ctx, req.(*ReqLoginByToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountByTGUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetAccountByTGUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountByTGUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccountByTGUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountByTGUser(ctx, req.(*ReqGetAccountByTGUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccountByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountByUserId(ctx, req.(*ReqUserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_BatchGetAccountsByUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUserIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).BatchGetAccountsByUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_BatchGetAccountsByUserIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).BatchGetAccountsByUserIds(ctx, req.(*ReqUserIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SetAccountTGLan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSetAccountTGLan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SetAccountTGLan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SetAccountTGLan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SetAccountTGLan(ctx, req.(*ReqSetAccountTGLan))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpb.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginTest",
			Handler:    _AccountService_LoginTest_Handler,
		},
		{
			MethodName: "GenerateLoginToken",
			Handler:    _AccountService_GenerateLoginToken_Handler,
		},
		{
			MethodName: "LoginByToken",
			Handler:    _AccountService_LoginByToken_Handler,
		},
		{
			MethodName: "GetAccountByTGUser",
			Handler:    _AccountService_GetAccountByTGUser_Handler,
		},
		{
			MethodName: "GetAccountByUserId",
			Handler:    _AccountService_GetAccountByUserId_Handler,
		},
		{
			MethodName: "BatchGetAccountsByUserIds",
			Handler:    _AccountService_BatchGetAccountsByUserIds_Handler,
		},
		{
			MethodName: "SetAccountTGLan",
			Handler:    _AccountService_SetAccountTGLan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_account.proto",
}
