// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: http_gm.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CReqAdminLoginByPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CReqAdminLoginByPassword) Reset() {
	*x = CReqAdminLoginByPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqAdminLoginByPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqAdminLoginByPassword) ProtoMessage() {}

func (x *CReqAdminLoginByPassword) ProtoReflect() protoreflect.Message {
	mi := &file_http_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqAdminLoginByPassword.ProtoReflect.Descriptor instead.
func (*CReqAdminLoginByPassword) Descriptor() ([]byte, []int) {
	return file_http_gm_proto_rawDescGZIP(), []int{0}
}

func (x *CReqAdminLoginByPassword) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CReqAdminLoginByPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CResAdminLoginByPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CResAdminLoginByPassword) Reset() {
	*x = CResAdminLoginByPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResAdminLoginByPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResAdminLoginByPassword) ProtoMessage() {}

func (x *CResAdminLoginByPassword) ProtoReflect() protoreflect.Message {
	mi := &file_http_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResAdminLoginByPassword.ProtoReflect.Descriptor instead.
func (*CResAdminLoginByPassword) Descriptor() ([]byte, []int) {
	return file_http_gm_proto_rawDescGZIP(), []int{1}
}

func (x *CResAdminLoginByPassword) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CReqAdminRecoverEnergy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CReqAdminRecoverEnergy) Reset() {
	*x = CReqAdminRecoverEnergy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqAdminRecoverEnergy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqAdminRecoverEnergy) ProtoMessage() {}

func (x *CReqAdminRecoverEnergy) ProtoReflect() protoreflect.Message {
	mi := &file_http_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqAdminRecoverEnergy.ProtoReflect.Descriptor instead.
func (*CReqAdminRecoverEnergy) Descriptor() ([]byte, []int) {
	return file_http_gm_proto_rawDescGZIP(), []int{2}
}

func (x *CReqAdminRecoverEnergy) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CReqAdminFreezeAccountTrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CReqAdminFreezeAccountTrade) Reset() {
	*x = CReqAdminFreezeAccountTrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_gm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqAdminFreezeAccountTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqAdminFreezeAccountTrade) ProtoMessage() {}

func (x *CReqAdminFreezeAccountTrade) ProtoReflect() protoreflect.Message {
	mi := &file_http_gm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqAdminFreezeAccountTrade.ProtoReflect.Descriptor instead.
func (*CReqAdminFreezeAccountTrade) Descriptor() ([]byte, []int) {
	return file_http_gm_proto_rawDescGZIP(), []int{3}
}

func (x *CReqAdminFreezeAccountTrade) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_http_gm_proto protoreflect.FileDescriptor

var file_http_gm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x70, 0x62, 0x22, 0x50, 0x0a, 0x18, 0x43, 0x52, 0x65, 0x71, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x30, 0x0a, 0x18, 0x43, 0x52, 0x65, 0x73, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a, 0x16, 0x43, 0x52, 0x65, 0x71,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1b, 0x43,
	0x52, 0x65, 0x71, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_gm_proto_rawDescOnce sync.Once
	file_http_gm_proto_rawDescData = file_http_gm_proto_rawDesc
)

func file_http_gm_proto_rawDescGZIP() []byte {
	file_http_gm_proto_rawDescOnce.Do(func() {
		file_http_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_gm_proto_rawDescData)
	})
	return file_http_gm_proto_rawDescData
}

var file_http_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_http_gm_proto_goTypes = []interface{}{
	(*CReqAdminLoginByPassword)(nil),    // 0: mpb.CReqAdminLoginByPassword
	(*CResAdminLoginByPassword)(nil),    // 1: mpb.CResAdminLoginByPassword
	(*CReqAdminRecoverEnergy)(nil),      // 2: mpb.CReqAdminRecoverEnergy
	(*CReqAdminFreezeAccountTrade)(nil), // 3: mpb.CReqAdminFreezeAccountTrade
}
var file_http_gm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_gm_proto_init() }
func file_http_gm_proto_init() {
	if File_http_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_http_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqAdminLoginByPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResAdminLoginByPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqAdminRecoverEnergy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_gm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqAdminFreezeAccountTrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_gm_proto_goTypes,
		DependencyIndexes: file_http_gm_proto_depIdxs,
		MessageInfos:      file_http_gm_proto_msgTypes,
	}.Build()
	File_http_gm_proto = out.File
	file_http_gm_proto_rawDesc = nil
	file_http_gm_proto_goTypes = nil
	file_http_gm_proto_depIdxs = nil
}
