// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: http_item.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// item
type CResGetItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items                 []*Item                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	BaseEquips            []*BaseEquip            `protobuf:"bytes,2,rep,name=base_equips,json=baseEquips,proto3" json:"base_equips,omitempty"`
	NftEquips             []*NFTEquip             `protobuf:"bytes,3,rep,name=nft_equips,json=nftEquips,proto3" json:"nft_equips,omitempty"`
	Mana                  uint64                  `protobuf:"varint,4,opt,name=mana,proto3" json:"mana,omitempty"`
	BaseEquipUpgradeInfos []*BaseEquipUpgradeInfo `protobuf:"bytes,5,rep,name=base_equip_upgrade_infos,json=baseEquipUpgradeInfos,proto3" json:"base_equip_upgrade_infos,omitempty"`
}

func (x *CResGetItems) Reset() {
	*x = CResGetItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResGetItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResGetItems) ProtoMessage() {}

func (x *CResGetItems) ProtoReflect() protoreflect.Message {
	mi := &file_http_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResGetItems.ProtoReflect.Descriptor instead.
func (*CResGetItems) Descriptor() ([]byte, []int) {
	return file_http_item_proto_rawDescGZIP(), []int{0}
}

func (x *CResGetItems) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CResGetItems) GetBaseEquips() []*BaseEquip {
	if x != nil {
		return x.BaseEquips
	}
	return nil
}

func (x *CResGetItems) GetNftEquips() []*NFTEquip {
	if x != nil {
		return x.NftEquips
	}
	return nil
}

func (x *CResGetItems) GetMana() uint64 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *CResGetItems) GetBaseEquipUpgradeInfos() []*BaseEquipUpgradeInfo {
	if x != nil {
		return x.BaseEquipUpgradeInfos
	}
	return nil
}

type CReqUpgradeBaseEquipStar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquiptType EItem_BaseEquipType `protobuf:"varint,1,opt,name=equipt_type,json=equiptType,proto3,enum=mpb.EItem_BaseEquipType" json:"equipt_type,omitempty"`
	CurStar    uint32              `protobuf:"varint,2,opt,name=cur_star,json=curStar,proto3" json:"cur_star,omitempty"`
}

func (x *CReqUpgradeBaseEquipStar) Reset() {
	*x = CReqUpgradeBaseEquipStar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqUpgradeBaseEquipStar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqUpgradeBaseEquipStar) ProtoMessage() {}

func (x *CReqUpgradeBaseEquipStar) ProtoReflect() protoreflect.Message {
	mi := &file_http_item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqUpgradeBaseEquipStar.ProtoReflect.Descriptor instead.
func (*CReqUpgradeBaseEquipStar) Descriptor() ([]byte, []int) {
	return file_http_item_proto_rawDescGZIP(), []int{1}
}

func (x *CReqUpgradeBaseEquipStar) GetEquiptType() EItem_BaseEquipType {
	if x != nil {
		return x.EquiptType
	}
	return EItem_BaseEquipType_None
}

func (x *CReqUpgradeBaseEquipStar) GetCurStar() uint32 {
	if x != nil {
		return x.CurStar
	}
	return 0
}

type CResUpgradeBaseEquipStar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewStar uint32 `protobuf:"varint,2,opt,name=new_star,json=newStar,proto3" json:"new_star,omitempty"`
}

func (x *CResUpgradeBaseEquipStar) Reset() {
	*x = CResUpgradeBaseEquipStar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_item_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResUpgradeBaseEquipStar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResUpgradeBaseEquipStar) ProtoMessage() {}

func (x *CResUpgradeBaseEquipStar) ProtoReflect() protoreflect.Message {
	mi := &file_http_item_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResUpgradeBaseEquipStar.ProtoReflect.Descriptor instead.
func (*CResUpgradeBaseEquipStar) Descriptor() ([]byte, []int) {
	return file_http_item_proto_rawDescGZIP(), []int{2}
}

func (x *CResUpgradeBaseEquipStar) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CResUpgradeBaseEquipStar) GetNewStar() uint32 {
	if x != nil {
		return x.NewStar
	}
	return 0
}

type CReqUpgradeBaseEquipLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquiptType EItem_BaseEquipType `protobuf:"varint,1,opt,name=equipt_type,json=equiptType,proto3,enum=mpb.EItem_BaseEquipType" json:"equipt_type,omitempty"`
	CurLevel   uint32              `protobuf:"varint,2,opt,name=cur_level,json=curLevel,proto3" json:"cur_level,omitempty"`
}

func (x *CReqUpgradeBaseEquipLevel) Reset() {
	*x = CReqUpgradeBaseEquipLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_item_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqUpgradeBaseEquipLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqUpgradeBaseEquipLevel) ProtoMessage() {}

func (x *CReqUpgradeBaseEquipLevel) ProtoReflect() protoreflect.Message {
	mi := &file_http_item_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqUpgradeBaseEquipLevel.ProtoReflect.Descriptor instead.
func (*CReqUpgradeBaseEquipLevel) Descriptor() ([]byte, []int) {
	return file_http_item_proto_rawDescGZIP(), []int{3}
}

func (x *CReqUpgradeBaseEquipLevel) GetEquiptType() EItem_BaseEquipType {
	if x != nil {
		return x.EquiptType
	}
	return EItem_BaseEquipType_None
}

func (x *CReqUpgradeBaseEquipLevel) GetCurLevel() uint32 {
	if x != nil {
		return x.CurLevel
	}
	return 0
}

type CResUpgradeBaseEquipLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewLevel uint32 `protobuf:"varint,2,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
}

func (x *CResUpgradeBaseEquipLevel) Reset() {
	*x = CResUpgradeBaseEquipLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_item_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResUpgradeBaseEquipLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResUpgradeBaseEquipLevel) ProtoMessage() {}

func (x *CResUpgradeBaseEquipLevel) ProtoReflect() protoreflect.Message {
	mi := &file_http_item_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResUpgradeBaseEquipLevel.ProtoReflect.Descriptor instead.
func (*CResUpgradeBaseEquipLevel) Descriptor() ([]byte, []int) {
	return file_http_item_proto_rawDescGZIP(), []int{4}
}

func (x *CResUpgradeBaseEquipLevel) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CResUpgradeBaseEquipLevel) GetNewLevel() uint32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

var File_http_item_proto protoreflect.FileDescriptor

var file_http_item_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x0c, 0x43, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x6e, 0x66, 0x74, 0x5f, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x4e, 0x46, 0x54, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x09, 0x6e, 0x66, 0x74, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x12, 0x52, 0x0a, 0x18, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x55, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x62, 0x61, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x70, 0x0a,
	0x18, 0x43, 0x52, 0x65, 0x71, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x74, 0x61, 0x72, 0x12, 0x39, 0x0a, 0x0b, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x75, 0x72, 0x53, 0x74, 0x61, 0x72, 0x22,
	0x4f, 0x0a, 0x18, 0x43, 0x52, 0x65, 0x73, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x72,
	0x22, 0x73, 0x0a, 0x19, 0x43, 0x52, 0x65, 0x71, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x39, 0x0a,
	0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x52, 0x0a, 0x19, 0x43, 0x52, 0x65, 0x73, 0x55, 0x70, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x42, 0x61, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x65, 0x77, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_item_proto_rawDescOnce sync.Once
	file_http_item_proto_rawDescData = file_http_item_proto_rawDesc
)

func file_http_item_proto_rawDescGZIP() []byte {
	file_http_item_proto_rawDescOnce.Do(func() {
		file_http_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_item_proto_rawDescData)
	})
	return file_http_item_proto_rawDescData
}

var file_http_item_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_http_item_proto_goTypes = []interface{}{
	(*CResGetItems)(nil),              // 0: mpb.CResGetItems
	(*CReqUpgradeBaseEquipStar)(nil),  // 1: mpb.CReqUpgradeBaseEquipStar
	(*CResUpgradeBaseEquipStar)(nil),  // 2: mpb.CResUpgradeBaseEquipStar
	(*CReqUpgradeBaseEquipLevel)(nil), // 3: mpb.CReqUpgradeBaseEquipLevel
	(*CResUpgradeBaseEquipLevel)(nil), // 4: mpb.CResUpgradeBaseEquipLevel
	(*Item)(nil),                      // 5: mpb.Item
	(*BaseEquip)(nil),                 // 6: mpb.BaseEquip
	(*NFTEquip)(nil),                  // 7: mpb.NFTEquip
	(*BaseEquipUpgradeInfo)(nil),      // 8: mpb.BaseEquipUpgradeInfo
	(EItem_BaseEquipType)(0),          // 9: mpb.EItem.BaseEquipType
}
var file_http_item_proto_depIdxs = []int32{
	5, // 0: mpb.CResGetItems.items:type_name -> mpb.Item
	6, // 1: mpb.CResGetItems.base_equips:type_name -> mpb.BaseEquip
	7, // 2: mpb.CResGetItems.nft_equips:type_name -> mpb.NFTEquip
	8, // 3: mpb.CResGetItems.base_equip_upgrade_infos:type_name -> mpb.BaseEquipUpgradeInfo
	9, // 4: mpb.CReqUpgradeBaseEquipStar.equipt_type:type_name -> mpb.EItem.BaseEquipType
	9, // 5: mpb.CReqUpgradeBaseEquipLevel.equipt_type:type_name -> mpb.EItem.BaseEquipType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_http_item_proto_init() }
func file_http_item_proto_init() {
	if File_http_item_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_http_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResGetItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqUpgradeBaseEquipStar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_item_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResUpgradeBaseEquipStar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_item_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqUpgradeBaseEquipLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_item_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResUpgradeBaseEquipLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_item_proto_goTypes,
		DependencyIndexes: file_http_item_proto_depIdxs,
		MessageInfos:      file_http_item_proto_msgTypes,
	}.Build()
	File_http_item_proto = out.File
	file_http_item_proto_rawDesc = nil
	file_http_item_proto_goTypes = nil
	file_http_item_proto_depIdxs = nil
}
