// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: http_market.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CReqGetGoodsOrdersOnSell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId  uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PageNum uint32 `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
}

func (x *CReqGetGoodsOrdersOnSell) Reset() {
	*x = CReqGetGoodsOrdersOnSell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqGetGoodsOrdersOnSell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqGetGoodsOrdersOnSell) ProtoMessage() {}

func (x *CReqGetGoodsOrdersOnSell) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqGetGoodsOrdersOnSell.ProtoReflect.Descriptor instead.
func (*CReqGetGoodsOrdersOnSell) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{0}
}

func (x *CReqGetGoodsOrdersOnSell) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CReqGetGoodsOrdersOnSell) GetPageNum() uint32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type CResGetGoodsOrdersOnSell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   uint32        `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PageNum  uint32        `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Orders   []*GoodsOrder `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	OrderCnt uint32        `protobuf:"varint,4,opt,name=order_cnt,json=orderCnt,proto3" json:"order_cnt,omitempty"`
}

func (x *CResGetGoodsOrdersOnSell) Reset() {
	*x = CResGetGoodsOrdersOnSell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResGetGoodsOrdersOnSell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResGetGoodsOrdersOnSell) ProtoMessage() {}

func (x *CResGetGoodsOrdersOnSell) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResGetGoodsOrdersOnSell.ProtoReflect.Descriptor instead.
func (*CResGetGoodsOrdersOnSell) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{1}
}

func (x *CResGetGoodsOrdersOnSell) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CResGetGoodsOrdersOnSell) GetPageNum() uint32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *CResGetGoodsOrdersOnSell) GetOrders() []*GoodsOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *CResGetGoodsOrdersOnSell) GetOrderCnt() uint32 {
	if x != nil {
		return x.OrderCnt
	}
	return 0
}

type CResGetMyGoodsOrdersOnSell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*GoodsOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *CResGetMyGoodsOrdersOnSell) Reset() {
	*x = CResGetMyGoodsOrdersOnSell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResGetMyGoodsOrdersOnSell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResGetMyGoodsOrdersOnSell) ProtoMessage() {}

func (x *CResGetMyGoodsOrdersOnSell) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResGetMyGoodsOrdersOnSell.ProtoReflect.Descriptor instead.
func (*CResGetMyGoodsOrdersOnSell) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{2}
}

func (x *CResGetMyGoodsOrdersOnSell) GetOrders() []*GoodsOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CReqPublishGoodsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Num    uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Price  uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CReqPublishGoodsOrder) Reset() {
	*x = CReqPublishGoodsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqPublishGoodsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqPublishGoodsOrder) ProtoMessage() {}

func (x *CReqPublishGoodsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqPublishGoodsOrder.ProtoReflect.Descriptor instead.
func (*CReqPublishGoodsOrder) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{3}
}

func (x *CReqPublishGoodsOrder) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CReqPublishGoodsOrder) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CReqPublishGoodsOrder) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CReqPurchaseGoodsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUuid uint64 `protobuf:"varint,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
}

func (x *CReqPurchaseGoodsOrder) Reset() {
	*x = CReqPurchaseGoodsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqPurchaseGoodsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqPurchaseGoodsOrder) ProtoMessage() {}

func (x *CReqPurchaseGoodsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqPurchaseGoodsOrder.ProtoReflect.Descriptor instead.
func (*CReqPurchaseGoodsOrder) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{4}
}

func (x *CReqPurchaseGoodsOrder) GetOrderUuid() uint64 {
	if x != nil {
		return x.OrderUuid
	}
	return 0
}

type CResPurchaseGoodsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods    *Item  `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
	ManaCost uint64 `protobuf:"varint,2,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
	ManaLeft uint64 `protobuf:"varint,3,opt,name=mana_left,json=manaLeft,proto3" json:"mana_left,omitempty"`
}

func (x *CResPurchaseGoodsOrder) Reset() {
	*x = CResPurchaseGoodsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResPurchaseGoodsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResPurchaseGoodsOrder) ProtoMessage() {}

func (x *CResPurchaseGoodsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResPurchaseGoodsOrder.ProtoReflect.Descriptor instead.
func (*CResPurchaseGoodsOrder) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{5}
}

func (x *CResPurchaseGoodsOrder) GetGoods() *Item {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *CResPurchaseGoodsOrder) GetManaCost() uint64 {
	if x != nil {
		return x.ManaCost
	}
	return 0
}

func (x *CResPurchaseGoodsOrder) GetManaLeft() uint64 {
	if x != nil {
		return x.ManaLeft
	}
	return 0
}

type CReqTakeOffGoodsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUuid uint64 `protobuf:"varint,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
}

func (x *CReqTakeOffGoodsOrder) Reset() {
	*x = CReqTakeOffGoodsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqTakeOffGoodsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqTakeOffGoodsOrder) ProtoMessage() {}

func (x *CReqTakeOffGoodsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqTakeOffGoodsOrder.ProtoReflect.Descriptor instead.
func (*CReqTakeOffGoodsOrder) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{6}
}

func (x *CReqTakeOffGoodsOrder) GetOrderUuid() uint64 {
	if x != nil {
		return x.OrderUuid
	}
	return 0
}

type CResTakeOffGoodsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddItem    *Item `protobuf:"bytes,1,opt,name=add_item,json=addItem,proto3" json:"add_item,omitempty"`
	UpdateItem *Item `protobuf:"bytes,2,opt,name=update_item,json=updateItem,proto3" json:"update_item,omitempty"`
}

func (x *CResTakeOffGoodsOrder) Reset() {
	*x = CResTakeOffGoodsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_market_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResTakeOffGoodsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResTakeOffGoodsOrder) ProtoMessage() {}

func (x *CResTakeOffGoodsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_http_market_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResTakeOffGoodsOrder.ProtoReflect.Descriptor instead.
func (*CResTakeOffGoodsOrder) Descriptor() ([]byte, []int) {
	return file_http_market_proto_rawDescGZIP(), []int{7}
}

func (x *CResTakeOffGoodsOrder) GetAddItem() *Item {
	if x != nil {
		return x.AddItem
	}
	return nil
}

func (x *CResTakeOffGoodsOrder) GetUpdateItem() *Item {
	if x != nil {
		return x.UpdateItem
	}
	return nil
}

var File_http_market_proto protoreflect.FileDescriptor

var file_http_market_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x18, 0x43, 0x52, 0x65, 0x71, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x4f, 0x6e, 0x53, 0x65,
	0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x94, 0x01, 0x0a, 0x18, 0x43, 0x52, 0x65, 0x73, 0x47,
	0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x4f, 0x6e, 0x53,
	0x65, 0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6e, 0x74, 0x22, 0x45, 0x0a,
	0x1a, 0x43, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x4f, 0x6e, 0x53, 0x65, 0x6c, 0x6c, 0x12, 0x27, 0x0a, 0x06, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x58, 0x0a, 0x15, 0x43, 0x52, 0x65, 0x71, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x37,
	0x0a, 0x16, 0x43, 0x52, 0x65, 0x71, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x73, 0x0a, 0x16, 0x43, 0x52, 0x65, 0x73, 0x50,
	0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x4c, 0x65, 0x66, 0x74, 0x22, 0x36, 0x0a, 0x15,
	0x43, 0x52, 0x65, 0x71, 0x54, 0x61, 0x6b, 0x65, 0x4f, 0x66, 0x66, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x55, 0x75, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x15, 0x43, 0x52, 0x65, 0x73, 0x54, 0x61, 0x6b, 0x65,
	0x4f, 0x66, 0x66, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x08, 0x61, 0x64, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_market_proto_rawDescOnce sync.Once
	file_http_market_proto_rawDescData = file_http_market_proto_rawDesc
)

func file_http_market_proto_rawDescGZIP() []byte {
	file_http_market_proto_rawDescOnce.Do(func() {
		file_http_market_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_market_proto_rawDescData)
	})
	return file_http_market_proto_rawDescData
}

var file_http_market_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_http_market_proto_goTypes = []interface{}{
	(*CReqGetGoodsOrdersOnSell)(nil),   // 0: mpb.CReqGetGoodsOrdersOnSell
	(*CResGetGoodsOrdersOnSell)(nil),   // 1: mpb.CResGetGoodsOrdersOnSell
	(*CResGetMyGoodsOrdersOnSell)(nil), // 2: mpb.CResGetMyGoodsOrdersOnSell
	(*CReqPublishGoodsOrder)(nil),      // 3: mpb.CReqPublishGoodsOrder
	(*CReqPurchaseGoodsOrder)(nil),     // 4: mpb.CReqPurchaseGoodsOrder
	(*CResPurchaseGoodsOrder)(nil),     // 5: mpb.CResPurchaseGoodsOrder
	(*CReqTakeOffGoodsOrder)(nil),      // 6: mpb.CReqTakeOffGoodsOrder
	(*CResTakeOffGoodsOrder)(nil),      // 7: mpb.CResTakeOffGoodsOrder
	(*GoodsOrder)(nil),                 // 8: mpb.GoodsOrder
	(*Item)(nil),                       // 9: mpb.Item
}
var file_http_market_proto_depIdxs = []int32{
	8, // 0: mpb.CResGetGoodsOrdersOnSell.orders:type_name -> mpb.GoodsOrder
	8, // 1: mpb.CResGetMyGoodsOrdersOnSell.orders:type_name -> mpb.GoodsOrder
	9, // 2: mpb.CResPurchaseGoodsOrder.goods:type_name -> mpb.Item
	9, // 3: mpb.CResTakeOffGoodsOrder.add_item:type_name -> mpb.Item
	9, // 4: mpb.CResTakeOffGoodsOrder.update_item:type_name -> mpb.Item
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_http_market_proto_init() }
func file_http_market_proto_init() {
	if File_http_market_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_http_market_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqGetGoodsOrdersOnSell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResGetGoodsOrdersOnSell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResGetMyGoodsOrdersOnSell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqPublishGoodsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqPurchaseGoodsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResPurchaseGoodsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqTakeOffGoodsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_market_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResTakeOffGoodsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_market_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_market_proto_goTypes,
		DependencyIndexes: file_http_market_proto_depIdxs,
		MessageInfos:      file_http_market_proto_msgTypes,
	}.Build()
	File_http_market_proto = out.File
	file_http_market_proto_rawDesc = nil
	file_http_market_proto_goTypes = nil
	file_http_market_proto_depIdxs = nil
}
